#
#Wed Mar 18 06:40:19 ECT 2026
acceptInsecureCerts=false
browserName=MicrosoftEdge
ms\:edgeOptions={args\=[--start-maximized, --window-size\=1920,1080, --test-type, --no-sandbox, --ignore-certificate-errors, --disable-popup-blocking, --disable-default-apps, --disable-infobars, --disable-gpu, --start-maximized, --window-size\=1920,1080, --remote-allow-origins\=*, --test-type, --no-sandbox, --ignore-certificate-errors, --disable-popup-blocking, --disable-default-apps, --disable-infobars, --disable-gpu], extensions\=[]}
